//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGrandeSAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int CodigoCompra { get; set; }
        public string Cliente { get; set; }
        public System.DateTime FechaCompraCliente { get; set; }
        public int Producto { get; set; }
        public int cantidad { get; set; }
        public int CostoUnidad { get; set; }
        public int CostoTotal { get; set; }
    }
}
