//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGrandeSAS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Inventarios
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public int CodigoBarras { get; set; }
        [Required]
        public string NombreProducto { get; set; }
        [Required]
        public string Categorias { get; set; }
        [Required]
        public string Bodega { get; set; }
        [Required]
        public long ValorUnidad { get; set; }
        [Required]
        public int unidades { get; set; }

        public long ValorTotal { get; set; }
        [Required]
        public int ValorDescuentounidad { get; set; }

        public int ValorUndDescuento { get; set; }

        public byte[] ImagenProducto { get; set; }
    }
}
