//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGrandeSAS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Usuario
    {
        [Key]
        public int Id { get; set; }
        [Required]       
        public string Nombres { get; set; }
        [Required]
        public string Apellidos { get; set; }
        [Required]
        public string Barrio { get; set; }

        public string FechaCreacion { get; set; }
        [Required]
        public string email { get; set; }
        [Required]
        public string usuario1 { get; set; }
        [Required]
        public string contraseña { get; set; }

        public string Rol { get; set; }
    }
}
